
name: deploy-me
'on':
    - push
jobs:
    deploy-me:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '16'
              env:
                  ACCESS_TOKEN: '${{ secrets.ACCESS_TOKEN }}'
            - run: npm install
            - run: npm run build
            - run: |
                  git clone https://${{secrets.ACCESS_TOKEN}}@github.com:qld-gov-au/matrix-projects-release.git
                  cp index.js clonedFolder/ -f
                  cd clonedFolder
                  git add .
                  git commit -m "$(date)"
                  git push
