
name: test github action
'on':
  - push
jobs:
  deploy-me:
    runs-on: ubuntu-latest
    steps:
        - name: Publish
          uses: qld-gov-au/gha-publish-to-git@master
          with:
            repository: ${{ secrets.TARGET_REPO }}
            git_ref: '${{ github.ref }}'
            branch: '${{ steps.extract_branch.outputs.branch }}'
            github_token: '${{ secrets.GH_TOKEN }}'
            github_pat: '${{ secrets.GH_PAT }}'
            source_folder: dist
            tag_branch: main
          if: success()

