
name: test github action
'on':
  - push
jobs:
  deploy-me:
    runs-on: ubuntu-latest
    steps:
        - name: Publish
          uses: qld-gov-au/gha-publish-to-git@master
          with:
            repository: qld-gov-au/matrix-projects-release
            git_ref: '${{ github.ref }}'
            branch: gh-pages
            github_pat: '${{ secrets.GH_PAT }}'
            source_folder: dist
            tag_branch: main
          if: success()

