
name: test github action
'on':
  - push
jobs:
  deploy-me:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: https://npm.pkg.github.com/
        env:
          ACCESS_TOKEN: '${{ secrets.ACCESS_TOKEN }}'
      - run: cd global-search && ls && npm install && npm run build
      - run: |
          git clone git@github.com:qld-gov-au/matrix-projects-release.git
          cd matrix-projects-release && mkdir global-search && cd ..
          cp global-search/dist/* matrix-projects-release/global-search/
          cd matrix-projects-release
          mkdir -p global-search && cd global-search
          git config --global user.name "asifamingov"
          git config --global user.email "asif.amin@smartservice.qld.gov.au"
          git add -A && git commit -m "commit message"
          git push
