
name: test github action
'on':
  - push
jobs:
  deploy-me:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: https://npm.pkg.github.com/
        env:
          ACCESS_TOKEN: '${{ secrets.ACCESS_TOKEN }}'
      - run: cd global-search && ls && npm install && npm run build
      - run: |
          git clone https://github.com/qld-gov-au/matrix-projects-release.git
          mkdir global-search && cd global-search
          git add .
          git commit -m "$(date)"
          git push
